# Bluetooth
CONFIG_ZMK_BLE=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y

# RGB Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y

# Ext Power (OLED power control via GPIO)
CONFIG_ZMK_EXT_POWER=y
